### ISSUE TITLE
npm install issues

### ISSUE THREAD

**Issue by andrewgoodchild** [mapbox/mapnik-omnivore#150]
Hi

I am having trouble npm installing mapnik-omnivore inside an Ubuntu 14.04 LTS docker container.
npm reports node-gyp is having trouble building node-gdal.   I can get the latest version of node-gdal to install fine.  But the version of node-gdal required by mapnik-omnivore wont build.

Does someone have a dockerfile I can look at that will help me get any dependencies right?

thanks, Andrew

**Comment by springmeyer** [comment]
`npm reports node-gyp is having trouble building node-gdal` Probably because you are using node v6? If so downgrade to node v4 until #138 lands (because only node-gdal@0.9.x supports node v6). Another common problem on docker is running as root: Either don't run as root or pass --unsafe-perm. More details at mapbox/node-pre-gyp#165.

**Comment by andrewgoodchild** [comment]
Thanks @springmeyer - that is very helpful.  I should have looked more closely at the version of node.

Do you think #138 is likely to happen soon?  Just so I know if I need to be working on a stop gap based on node 4.

**Comment by springmeyer** [comment]
Hopefully #138 will land in the next couple weeks.

**Comment by andrewgoodchild** [comment]
:-)
