### ISSUE TITLE
BigTIFF support

### ISSUE THREAD

**Issue by GretaCB** [mapbox/mapnik-omnivore#55]
Currently waiting on enabling BigTIFF ( > 4GB ) support in [`node-gdal`](https://github.com/naturalatlas/node-gdal).

All this entails is adding the `DBIGTIFF_SUPPORT` compile flag. I added this locally and ran a BigTIFF through `mapnik-omnivore` with success.

Note to self: validate BigTIFF filetype using http://www.awaresystems.be/imaging/tiff/bigtiff.html

cc @rclark @willwhite @springmeyer @camillacaros

**Comment by springmeyer** [comment]
@GretaCB want to provide a fix + test for bigtiff upstream in node-gdal? Let me know if you need anything from me to help with that.

**Comment by ljbade** [comment]
Dang, looks like I just ran into this problem opening a 26GB GeoTIFF in mapbox-studio

**Comment by ljbade** [comment]
@GretaCB I updated you PR to current master as well as pulling in the new node-gdal.

I just tested with mapbox-studio and it now works perfectly.

You should merge and get this into next mapbox-studio.

**Comment by GretaCB** [comment]
@ljbade awesome! I hadn't tested it out in studio yet. This is great news. I am currently troubleshooting bigtiff support with the newest node-gdal version in mapnik-omnivore.

I'll test it out in studio and push it through.

cc @springmeyer

**Comment by springmeyer** [comment]
Note: node-gdal is pinned in package.json because Studio requires custom node-gdal binaries to work without crashing. These binaries are available for node-gdal 0.3.1 but I've not built them for more recent versions yet. This is the reason that appveyor builds are failing for `msvs_toolset=14` (which is what Studio requires): https://ci.appveyor.com/project/Mapbox/mapnik-omnivore/build/1.0.313. So, https://github.com/mapbox/mapnik-omnivore/commit/b15d88b77dfd3ae0f95fe47f164dfaef366a324d is not viable yet for windows. The sequencing I propose is:

 - Battletest latest node-gdal/omnivore on unix to make sure it works fully with GeoTIFF and no further node-gdal releases are needed to support things
 - Once that is done, then ping me to make `msvs_toolset=14` binaries for node-gdal for the target node-gdal tag.
 - Then we can revisit getting mapnik-omnivore's appveyor builds passing and consider tagging a mapni-omnivore that can be used in Studio.

Alternatively @GretaCB if you want to run out a mapnik-omnivore tag with updated node-gdal without waiting for a studio/windows compatible build, you could pin studio to the current omnivore tag: https://github.com/mapbox/mapbox-studio/blob/mb-pages/package.json#L50. This would protect studio from breaking if an omnivore release came out that does not work fully on windows.

**Comment by GretaCB** [comment]
@springmeyer  I'm hesitant to pin studio to the current omnivore, since omnivore is failing on BigTIFFs currently. I'm actually not sure how bigtiffs worked for @ljbade since studio relies on mapnik-omnivore.

Im going to test out BigTIFF in the refactored mapnik-omnivore (we changed some of the raster processing) and see if I run into anything.

**Comment by springmeyer** [comment]
> I'm hesitant to pin studio to the current omnivore

Okay, I trust your judgement. What I mean is to pin Studio to a version of mapnik-om that works for windows (and does not yet work for bigtiffs). If you want to get studio working with bigtiffs on both unix and windows then I'll need to build binaries for latest node-gdal, which I'm not going to do until I need to. Sorry for the chicken'n egg situation. Will be on chat in ~ 30 min.

**Comment by rclark** [comment]
In the refactor branch I [disabled appveyor](https://github.com/mapbox/mapnik-omnivore/commit/e92a7a71f1bd25395a89c31b2a6211672818ac53). When we're ready lets open a ticket dedicated to getting it fixed?

**Comment by ljbade** [comment]
@GretaCB @springmeyer I made a mapbox-studio branch that points to the bigtiff omnivore to make it easier to test.

**Comment by springmeyer** [comment]
> lets open a ticket dedicated to getting it fixed?

Yes, assign to me and I'll get on this tomorrow.

**Comment by GretaCB** [comment]
BigTIFF support now in refactor PR  https://github.com/mapbox/mapnik-omnivore/pull/84

**Comment by springmeyer** [comment]
great, lets track at #84 (also as I mention at #84 node-gdal binaries are ready).
