### ISSUE TITLE
Consider output of gdal.SpatialReference object

### ISSUE THREAD

**Issue by rclark** [mapbox/mapnik-omnivore#79]
Currently omnivore reports projections as proj4 strings. I'm running into difficulties when I want to check if  a dataset is of a particular projection. I wonder if these problems would be alleviated by providing a `gdal.SpatialReference` object in the output of `omnivore.digest()`?

For example, after `gdalwarp` to put a tif into EPSG:3857, omnivore reports the following proj4 string as `metadata.projection`:

```
+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over
```

This string is not identical to the output from
```
> var gdal = require('gdal');
> gdal.SpatialReference.fromEPSG(3857).toProj4();
// +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs
```

The following attempted equality check fails:
```js
var gdal = require('gdal');
var omnivore = require('omnivore');

omnivore.digest('/spherical-merc.tif', function(err, metadata) {
  var reported = gdal.SpatialReference.fromProj4(metadata.projection);
  var expected = gdal.SpatialReference.fromEPSG(3857);
  console.log(reported.isSame(expected)); // false
});
```

cc @GretaCB @brandonreavis

**Comment by brandonreavis** [comment]
The difference in proj4 strings seems to be from passing it through node-srs to normalize projections [here](https://github.com/mapbox/mapnik-omnivore/blob/master/lib/datasource-processor.js#L439): 
```js
info.proj4 = srs.parse(ds.srs.toWKT()).proj4;
var ref = gdal.SpatialReference.fromProj4(info.proj4);
```
But yeah I agree that passing around something other than proj4 would be a good idea because converting to proj4 is lossy which causes even this to fail: 
```js
var srs1 = gdal.SpatialReference.fromEPSG(3857);
var srs2 = gdal.SpatialReference.fromProj4(srs1.toProj4());
console.log(srs1.isSame(srs2)); //false
```
Maybe use WKT at least?

**Comment by springmeyer** [comment]
Asking software to compare projections in anything but epsg codes is a bit of a snipe's hunt. So ya, `node-srs` is to blame/thank for these differences. That is the whole idea of node-srs: It tries to normalize the proj4 strings that might come out of various software (with a focus on mercator and bugs from failed attempts at describing EPSG:3857 in WKT and PROJ over the years) to make the snipe catchable in known otherwise impossible cases. Because GDAL, for instance, does not do this internally (to my knowledge) you can pass in various representations of mercator in WKT format (aka shapefiles) or proj4 format (like above) and get very different srs representations back.

So, to compare proj4 strings the idea is to parse both with node-srs beforehand and compare the resulting strings. This is helpful for software that only works in proj4 (like Mapnik).

Omnivore starting to store epsg as well as proj4 would be great I think to avoid this complexity for API's that a comfortable working in epsg codes. However, Mapnik never will work in epsg codes because Mapnik uses proj4 to support projections. And Proj4 stores the mapping between epsg codes -> proj4 literals in a csv file (at PROJ_LIB) which is a problem for high performance/multithreaded scenarios (https://github.com/mapnik/mapnik/issues/1579 and https://github.com/mapnik/mapnik/issues/1703)

**Comment by rclark** [comment]
At least on the gdal side I don't see a clear way to go from a SpatialReference object to an EPSG code. Metadata for mapnik is definitely the main goal of *mapnik*-omnivore, so given @springmeyer's description I'd say we stick to the `srs.parsed` proj4 strings.
